# Generated by Django 5.0.7 on 2024-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.CharField(max_length=20)),
                ('teachers_id', models.PositiveSmallIntegerField()),
                ('teachers_course', models.CharField(max_length=20)),
                ('teachers_class', models.CharField(max_length=20)),
                ('teachers_description', models.TextField()),
                ('teachers_occupation', models.CharField(max_length=20)),
                ('teaachers_hobby', models.CharField(max_length=20)),
                ('teachers_gender', models.CharField(max_length=20)),
            ],
        ),
    ]
