# Generated by Django 5.0.7 on 2024-07-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teachers_id',
            new_name='teachers_national_id',
        ),
    ]
