# Generated by Django 5.0.7 on 2024-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_teachers_id_teacher_teachers_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teachers_national_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teachers_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
        ),
    ]
