# Generated by Django 5.0.7 on 2024-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teachers_id',
            field=models.AutoField(default=3, primary_key=True, serialize=False),
        ),
    ]
