# Generated by Django 5.0.7 on 2024-07-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_teachers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teachers_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
