# Generated by Django 5.0.7 on 2024-07-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_teachers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teachers_id',
            new_name='teachers_national_id',
        ),
    ]
