# Generated by Django 5.1 on 2024-08-15 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_attendance',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='class',
            name='class_capacity',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='class',
            name='class_description',
            field=models.TextField(default='It is class full of girls'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
