# Generated by Django 5.1 on 2024-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_class_attendance_class_class_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
