# Generated by Django 5.0.7 on 2024-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=20)),
                ('assignment', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('exams', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
