# Generated by Django 5.0.7 on 2024-07-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
