# Generated by Django 5.0.7 on 2024-07-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_students_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students_course',
            new_name='students',
        ),
    ]
