# Generated by Django 5.0.7 on 2024-08-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_students_course_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
