# Generated by Django 5.0.7 on 2024-07-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teachers_course',
            field=models.CharField(default='Python', max_length=20),
        ),
    ]
    
