# Generated by Django 5.0.7 on 2024-07-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0004_alter_classperiod_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperiod',
            name='teacher',
        ),
    ]
