# Generated by Django 5.0.7 on 2024-07-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0005_remove_classperiod_teacher'),
        # ('teacher', '0003_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperiod',
            name='id',
        ),
        migrations.AddField(
            model_name='classperiod',
            name='class_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(default='teachers', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='course',
            field=models.CharField(max_length=20),
        ),
    ]
