# Generated by Django 5.0.7 on 2024-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0010_rename_class_id_classperiod_class_perod_id'),
        # ('teacher', '0007_alter_teacher_teaachers_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperiod',
            name='classroom_period',
        ),
        migrations.RemoveField(
            model_name='classperiod',
            name='teachers_period',
        ),
        migrations.AddField(
            model_name='classperiod',
            name='period',
            field=models.CharField(default='one year', max_length=20),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='teacherss',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='course',
            field=models.CharField(default='Python', max_length=20),
        ),
    ]
