# Generated by Django 5.0.7 on 2024-07-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0013_alter_classperiod_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classperiod',
            old_name='teacherss',
            new_name='teacher',
        ),
    ]
