# Generated by Django 5.0.7 on 2024-08-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0014_rename_teacherss_classperiod_teacher'),
        ('teachers', '0002_alter_teacher_teachers_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teachers.teacher'),
        ),
    ]
