# Generated by Django 5.1 on 2024-08-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0015_alter_classperiod_teacher'),
        ('teachers', '0003_alter_teacher_teachers_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classperiod',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
