# Generated by Django 5.0.7 on 2024-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_lecturer', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=20)),
                ('class_rep', models.CharField(max_length=20)),
                ('electricity', models.CharField(max_length=20)),
            ],
        ),
    ]
