# Generated by Django 5.0.7 on 2024-07-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='immediate_contact',
            field=models.CharField(max_length=20),
        ),
    ]
