# Generated by Django 5.0.7 on 2024-07-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_bio_alter_students_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='country',
            field=models.CharField(default='Kenya', max_length=20),
        ),
    ]
