# Generated by Django 5.0.7 on 2024-08-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_course_students'),
        ('student', '0003_alter_students_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
