# Generated by Django 5.1 on 2024-08-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('student', '0004_students_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AlterField(
            model_name='students',
            name='bio',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
