# Generated by Django 5.1 on 2024-08-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_students_classes_alter_students_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
